language: node_js
node_js:
- '6'
before_script:
- npm install -g webpack
- npm install -g codecov
before_deploy:
- npm run deploy
deploy:
  provider: releases
  api_key:
    secure: 3aGehZdikv6wueuQ+Pc6oo3gMD1B54FdzEkdl7HS/7BNQcK0v6aYWSACxuHIZPxDcXtfgODhsf4OnzVZMDHlHcbv1BP0DuZ8i4fF6qsHVduItEYryYIhwVUhLSFGX/4iDPPG/U5GJFuCb2tROzrqr3wPoWMMXzMfpi2uFJhUTk3yrCvnAndUj4C0XE3rBnQERzxHsXdGRd2EMyFsYxduDtiVUPs+cEwQQieN9LXeHeeJpf7PFKz6HvUyXkD5PjOWmJ3nqJ9/eN7xJ7jUun+eVSSaEtoKHYDTfcmfY1ru66zdJ5vtvRpV9PyZ4OwgFEsDnthePsW1SCeTySmZUzkSeKsu1EB8LVvrsMifxaS+vhALPbl9HIx+n20UYs1domyOdp7tQzs04qmiybhMT/EgEYFQZa/eZH6Yq04Zk/ZXMjQ/0R+LAq6m6MnRrmYQ1W8fp3++Rl/W69wtlsYWOTeNz500jOTyBF1SlbZ69RAEZmQFqyVP66Z7UBdKGR/fAxMdFM6fETxNzllu19QFFI6jSvnqnY1PN0HuRpXPXzlZ3I3TO/txSXpDTRUnBTy8G0hXe7MfUqv+mjnsbmD+5Q7AvqS5gLVnsTYTu1MyGJqgCmljkOIORxdqwtFq0AcsnF7qoW3MiUwxtvn4MkeoekXTISPuI9V06DUHb53ZD7eqrF4=
  file_glob: true
  file: ./dist/JAlgoArena-UI-*.zip
  skip_cleanup: true
  on:
    repo: antonina18/JAlgoArena-UI
    tags: true
addons:
  code_climate:
    repo_token: 9e2995be6eae3d6663fd00f8db738c4bf306f9f7779c8f1c4fb0f5d0d56c17e0
