language: node_js
node_js:
- '6'
before_script:
- npm install -g webpack
- npm install -g codecov
before_deploy:
- npm run deploy
deploy:
  provider: releases
  api_key:
    secure: wI6ejYbbl4Tk59/cn45YOgAOrjDaw+l1BlrsFeVTo4Jiu/wLAA19vV0JiMc9O2EU3pBaXoprPQl1B7eGSH/di8x9aMysK3PNaKoXGFowykDLU6BjQ+viWKNbZI9gqSSmx9Ex+a7QB3zTgvKfQJiM25PqEUo9vvUBDbF2YqMlAAJSxpdJzhYoq+pnvqugevjH5IqpW0IjlP1NpvypVwxcQotX4TQA05Izoa7An3L7qwhDqZhWsDkqqqp1Da5bpMMc0B4qV0V1vBMxBbc4D+6s1CKR8gAerhieT69fV8mr2B6kDKxi9fbEvuS9xBH/HjhqGtuC1OiQOHYMSs+J8pX/t+EJ/wdXv8GLHsKMb9ErTicaEqyT3LfBw6Axdvnm+Cr8EqaP5Ma0C+iOd/KZ2AFl9daawjyFOFPqQoa8KQcHL46C96AC6kLyOQSN/SN2Jl98P5P4pP64N3N8ljScuFO/VBlYXLqKrgivDMnnynqg/ZvWzM93KXjSZnx4E8ElPQSAlZdCS5crbfTL/vV2Zxouc1u+ihUWpqhLtZquBsqKl+u/h2/JaqG1jO2SXPPp5tTIR4izVxFVF6cFL57F27/i1QdtUEG5PeTiHbsGZN4iKIaLDbQC+UJsLSxszdYJ8sxNFOLxnG1HbggEtABE/Nx/eVvvzkGhmB+zPXesDBpx8l0=
  file_glob: true
  file: ./dist/JAlgoArena-UI-*.zip
  skip_cleanup: true
  on:
    repo: antonina18/JAlgoArena-UI
    tags: true
addons:
  code_climate:
    repo_token: 9e2995be6eae3d6663fd00f8db738c4bf306f9f7779c8f1c4fb0f5d0d56c17e0
